### ISSUE TITLE
[Feature Request] [SortPlus] Add Sort by Date

### ISSUE THREAD

**Issue by JustSxm** [Delusoire/spicetify-extensions#1]
Possible to add Sort by Date (Newest to Oldest)? This allows to listen to the new songs of an artist easily.

Thanks!

**Comment by Delusoire** [comment]
Added in
c31dcfd46121fcfc06c1b9c86ceae00a3c72963a
ccf1ff42630bc038119d20cb5c458e3f3d1be343
