### ISSUE TITLE
keyboard-shortcuts question

### ISSUE THREAD

**Issue by Cookdao** [Delusoire/spicetify-extensions#10]
Dont know how to use this plug ,can i get some instruction?

**Comment by Delusoire** [comment]
Here is a list of keybinds that are currently available and will be added to the readme. The default keybinds are as follows:

- `s`: Enter 'sneak' mode, which is similar to vim-sneak.
- `shift + s`: Reload Spotify with developer mode enabled.
- `tab`: Go to the next page from the navigation bar.
- `shift + tab`: Go to the previous page from the navigation bar.
- `shift + h`: Go to the previous page from the history.
- `shift + l`: Go to the next page from the history.
- `j`: Scroll down.
- `k`: Scroll up.
- `g`: Scroll to the top.
- `shift + g`: Scroll to the bottom.
- `m`: Like/unlike the current playing song.
- `/`: Shortcut for searching.
