### ISSUE TITLE
Sort by Play Count No Longer Working

### ISSUE THREAD

**Issue by Aquaed** [Delusoire/spicetify-extensions#12]
Sort Plus extension not showing up in right click menu anymore.

**Comment by Delusoire** [comment]
Can you make sure that you're on the latest version of spotify, your spicetify is up to date, and that you're using the marketplace version of the extension?

**Comment by Aquaed** [comment]
I am

**Comment by Delusoire** [comment]
There was a bug where the sort menu wouldn't show for tracks, but it is now fixed. Can you check if your problem is fixed?

**Comment by Aquaed** [comment]
Not quite, i'll try a clean install.

**Comment by Aquaed** [comment]
Still not quite working

**Comment by Aquaed** [comment]
Worked after complete reinstallation. Thanks

**Comment by Delusoire** [comment]
Oh, glad you worked it out! However, I wonder what would have caused this issue as Marketplace is supposed to refetch the extension every time Spotify reloads. I'm closing this issue, but if you run into other problems you can just open a new one.
