### ISSUE TITLE
show-the-genres not working

### ISSUE THREAD

**Issue by harbassan** [Delusoire/spicetify-extensions#13]
The track genre isn't showing up at all.

Logs:
![image](https://github.com/Delusoire/spicetify-extensions/assets/84175605/db57f131-e7d3-49f4-adc4-229664b00aba)

Btw, I think you should add preview images to your readme for each extension, it would genuinely be much better than just an orange square.

**Comment by Delusoire** [comment]
You can't get access to the Last FM genres without an API Key. I used to provide a default one, but it quickly got rate-limited and became barely usable. So if you want to get genres you need to: Create a Last FM account, Generate an API Key, and add the key to the settings.
About the preview images, I plan to add them, just haven't gotten around to doing that yet.

**Comment by harbassan** [comment]
Sweet that works now, maybe writing that somewhere would help. 

I've also encountered another error after providing the api-key, causing the artists page genre not to work:

![image](https://github.com/Delusoire/spicetify-extensions/assets/84175605/8f04a190-dd97-46bc-b473-2196a1f561b3)

**Comment by ffffionn** [comment]
where to put the API key? documentation would be great on this

**Comment by teamwolfyta** [comment]
@ffffionn In your Spotify Client, Click your profile icon in the top right and click settings, Scroll down to the bottom and you will see a section titled "Show the Genres", Under it you will see the place you put your Last.fm API key. To get an API key go to [here](https://www.last.fm/api/account/create) and just fill in the information, When you've done that it will give you an API key and a Shared secret, Ignore the Shared secret but copy the API Key into the box next to were it say's "last.fm API Key".

**Comment by ffffionn** [comment]
Huh, I don't seem to have that option there at all (have the Tetrax-10 one installed)

**Comment by Delusoire** [comment]
> Huh, I don't seem to have that option there at all (have the Tetrax-10 one installed)

This is not Tetrax's extension. And please don't use closed / unrelated issues to ask for help; Open your own issue, or ask on the official Spicetify discord.

**Comment by lihuelworks** [comment]
I also don't have the "Show-your-genre" option on my settings, using Spicetify. Are there docs somewhere for this?

**Comment by lihuelworks** [comment]
Just for everyone reading this, Spotify changed some things, so you won't see the "Show-your-genres" option in settings. Details covered by https://github.com/Delusoire/spicetify-extensions/issues/25#issuecomment-1949941113
