### ISSUE TITLE
keyboard-shortcuts, like shortcut not working.

### ISSUE THREAD

**Issue by Sancoraa** [Delusoire/spicetify-extensions#14]
Pretty much the title

Tried every other shortcuts, all are working fine, but when I press the like shortcut (m), Spotify shows me a red banner "Something went wrong"
Default Spotify's like shortcut works fine

**Comment by Switchbladd** [comment]
+1, it unlike if track already liked but won't like if it's not / Latest spotify & spicetify versions

**Comment by Delusoire** [comment]
Indeed, there was a problem with how I handled toggling the liked state. I null check was missing but it's now fixed following commit #db49717. Thanks for reporting the bug!
