### ISSUE TITLE
Sort-plus acting weird

### ISSUE THREAD

**Issue by Switchbladd** [Delusoire/spicetify-extensions#15]
I just started using Spicecify and installed like 20+ apps/snippets/extensions and the only extension that does not work as intended is sort-plus. 
I tested it on 13 song playlist and every time I try to sort it by any parameter it adds all the songs to the queue in the same order as they are in a playlist (meaning it doesn't sort anything) and even more, it adds it like multiple times, 5 or 6 (of every song). Sometimes nothing happens, no errors, no queue, no notifications, nothing. 
I've already tried reinstalling Spicetify, clean reinstalling Spotify, reinstalling extension multiple times, and reloading a PC, I even tried to run a virtual machine and downloaded Spotify and Spicetify on it and it still behaves the same which is odd because no one else seems to have this problem... 
![image](https://github.com/Delusoire/spicetify-extensions/assets/66808884/17e01f8f-4b7d-4058-a6d5-a273b399fe20)
The only thing that I didn't try is using another Spotify account but I doubt it has something to do with it...
Edit: and I've obviously tried different playlists

**Comment by Delusoire** [comment]
That happens because the queue context is set after the tracks are queued, and triggers the Spotify internals to make an infinite repeating context-queue (kind of like playing from any context). I can move the the setQueue to happen after the context is changed, although that's how I originally wrote it and I can only remember that it broke something else. I'll do some testing and see if it's stable now.

**Comment by Switchbladd** [comment]
Well, it seems like you fixed multiple-adding thing but the sorting itself is still not working for me, is that a problem on my side? Do you have any suggestions on what could cause that?
When I try to sort by popularity or true shuffle it simply adds the whole playlist to the queue without any changes (in the same order that it goes in the playlist) while the other 4 parameters (last fm ones and play count) do nothing at all, no notifications, no queue

**Comment by Delusoire** [comment]
I can't seem to reproduce your error, can you show your console logs/errors? To open devtools you need to run `spicetify enable-devtools` in the shell, and then hit `ctrl + shift + i` in the Spotify window.

**Comment by Switchbladd** [comment]
Sort by play count (nothing happens) -
![image](https://github.com/Delusoire/spicetify-extensions/assets/66808884/b6018717-c97d-434e-8578-67278641587f)
True shuffle (adds song to queue but does not randomize them) -
![image](https://github.com/Delusoire/spicetify-extensions/assets/66808884/7fe3391f-130a-42f0-b3f9-83a493def240)
Did clean install of both Spotify and Spicetify with no other extensions etc. enabled

**Comment by Delusoire** [comment]
You're not on the latest Spotify/Spicetify version, just to confirm what happens when you type `Spicetify.Snackbar`, `Spicetify.Snackbar.enqueueSnackbar`, `Spicetify.Snackbar.updater.enqueueSetState` in the console?

**Comment by Switchbladd** [comment]
![image](https://github.com/Delusoire/spicetify-extensions/assets/66808884/77249f6d-92cf-4df9-8d61-62a0c80c84a3)
Spotify downloaded from their site and Spicetify downloaded using [https://spicetify.app/docs/getting-started/](url) powershell commands

**Comment by Delusoire** [comment]
This is what it's supposed to look like:
![image](https://github.com/Delusoire/spicetify-extensions/assets/71462480/8bcce12c-8415-4d17-a4b9-f5c77f4f9ce5)
Can you post a screenshot of your: `three dots on the top left` => `Help` => `About Spotify` ?

**Comment by Switchbladd** [comment]
![image](https://github.com/Delusoire/spicetify-extensions/assets/66808884/b23ae717-7e1b-4c64-8f69-112fb08a9faa)

**Comment by Delusoire** [comment]
It seems like you're on a newer Spotify version than me. I guess I'm still not elligible for the update, but when I do recieve it i'll add support for 1.2.26.

**Comment by Switchbladd** [comment]
What is your version? I'll rollback mine

**Comment by Delusoire** [comment]
It's 1.2.25.1011

**Comment by Delusoire** [comment]
A Spicetify update was pushed, fixing Snackbar exposure. So now if you update your spicetify everything should be working fine.
