### ISSUE TITLE
Sort-Plus is not working

### ISSUE THREAD

**Issue by ghost** [Delusoire/spicetify-extensions#17]
I've marked all of these because I want to sort all the songs of an artist by date, I wanted them to be all together, and it's not working right now. When I click, nothing happens. (Your app didn't add the songs in the "Appears On" section before either. This is also a suggestion.) 
![Ekran görüntüsü 2023-12-13 153956](https://github.com/Delusoire/spicetify-extensions/assets/153736715/af5fdb92-5b09-4760-afb1-b795dab2964d)
I like the job you're doing, it would be great if you could fix this.

**Comment by Delusoire** [comment]
I was testing a few changes some hours ago, could be that you were served one of these testing versions. Try reloading Spotify, and hopefully, everything will be working again. I added a toggle for including the Appears On tracks, but it often results in having duplicate tracks from different sources. Do you prefer to only keep the first occurrence, or should I leave it as it is? Btw, if you enable All of the artist's discography then you should probably disable all the other toggles.

**Comment by ghost** [comment]
Thanks for coming back. "Appear On" really works. I don't really care about duplicated tracks, I'm a bit of a problematic (perfectionist) person, and I want all the songs that the artist has. However, I'm sorry to say, I did what they said, and still the "All of the artist's Discography" part doesn't work.(Even though I left this alone.) However, the "Popular Releases" section also prevents it from working when it is opened. When I open all of them and close these two, it works, but I can't get the result I want. When you turn them all off and open the "All of the artist's Discography" section, it doesn't work.

![Ekran görüntüsü 2023-12-13 170812](https://github.com/Delusoire/spicetify-extensions/assets/153736715/384d9d7d-cffd-4c0a-a436-939edb9a723d)
![Ekran görüntüsü 2023-12-13 171206](https://github.com/Delusoire/spicetify-extensions/assets/153736715/9b13e4da-5396-441a-822f-9a6b146d88c7)
![Ekran görüntüsü 2023-12-13 171224](https://github.com/Delusoire/spicetify-extensions/assets/153736715/7973ab05-8148-4209-9694-1bf4ac09e475)
I hope I've made myself clear. I mean, I want all the tracks of an artist. Duplications do not matter. I have a lot of respect for what you do, dude, and I don't know of any other application like this. That's why I share my troubles only with you.

**Comment by ghost** [comment]
What can I do to make them all work together? Is that impossible?

**Comment by Delusoire** [comment]
What I mean is  All Discography should include everything from the artist.

**Comment by ghost** [comment]
Even so, it doesn't work. It's only when I open it and close the others that nothing happens. Doesn't sorting.

**Comment by Delusoire** [comment]
Oh I see what the problem is, it has to do with GraphQL's api paging; I'll work on it

**Comment by ghost** [comment]
You're amazing, man. There are hundreds of questions I want to ask you. Still, I don't want to cause you any more trouble. Thank you very much.

**Comment by Delusoire** [comment]
I think it should be working now. And I'm glad that you're enjoying this extension!
If you have other problems with these extensions, just open a new issue
