### ISSUE TITLE
[Sort-Plus] Possible issue with sorting massive playlists (2k+)

### ISSUE THREAD

**Issue by otterbatch** [Delusoire/spicetify-extensions#18]
I am currently unable to get Sort-Plus to sort my 2.6k behemoth of a playlist using any of the possible options (Spotify Play Count, Popularity, Last.fm, etc.). Other smaller playlists of 100-700 songs seem to sort just fine. For all its complaints about lacking resources in the console, it barely touches on half my CPU and only the normal ~700mb of RAM.

![image](https://github.com/Delusoire/spicetify-extensions/assets/21991672/c9100deb-c3a4-4764-83ff-162b5404cfd4)

Not sure if this is possible to be fixed but thought I'd raise awareness to it nonetheless :) Keep up the great work!

**Comment by Delusoire** [comment]
This issue seems to be related to the browser itself; There is a hard-coded limit on how many requests can be sent. I guess I can modify the requests to wait for batches to resolve before sending more.

**Comment by Delusoire** [comment]
Also, LastFM bails at much smaller playlists, their API is heavily rate limited.

**Comment by Delusoire** [comment]
Just for testing, can you share an example of such a big playlist?

**Comment by otterbatch** [comment]
Sure thing! I went ahead and made a copy of my current playlist for ya, trash tunes and all.

https://open.spotify.com/playlist/52KnxTntig5oDKJ4m98ksl?si=J8d-4jc4SxuNmqVA9K6v_A&pi=u-4_cSCUPNQg-B

Hope the link works fine, and thanks a ton for the response!

**Comment by Delusoire** [comment]
Changed a few things, now all Spotify sort options are working for that playlist and probably for up to at least 10k tracks. However when sorting by Play count, the first 1000 requests are sent in parallel (which is fast). But after that limit is hit, subsequent requests are queued so that no more than 1000 requests are ever being processed, making everything much slower.

**Comment by otterbatch** [comment]
Seems to work perfectly so far, thank you! It's a shame about Last.fm, but I'll probably just try making separate smaller playlists for that. Thanks a ton again for the help!
