### ISSUE TITLE
Sort plus issue

### ISSUE THREAD

**Issue by Cookdao** [Delusoire/spicetify-extensions#20]
i delete the folder by accident. And when i wanna create an new playlist, it no reaction

**Comment by Delusoire** [comment]
You can either:
- type `localStorage["extensions:sort-plus:sortedPlaylistsFolderUri"] = undefined` in your devtools console and reload spotify, or
- you can choose whatever folder you want, right click on it, and select the appropriate action from the context menu.

**Comment by Cookdao** [comment]
thx for ansering. i try both method but didnt work out.
i use my another macbook to work. It works fine tho.
THxs anyway
