### ISSUE TITLE
Issues with Sort Plus

### ISSUE THREAD

**Issue by VPNforWindowsSub** [Delusoire/spicetify-extensions#22]
The sorting extension works well when sorting songs in the queue. However, it encounters issues when creating a new playlist with the sorted songs. Additionally, when attempting to reorder the current playlist, especially with large playlists, the app freezes.

I used to work with the [Sort-by-Play-count](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Sort-by-Play-count) extension by [Tetrax-10](https://github.com/Tetrax-10). It worked perfectly, allowing me to sort 3000 songs in the playlist and create a new playlist with them. Unfortunately, since that repository has been archived, the extension no longer functions. Could you please check if there's a way to draw inspiration from it and address the current issues?

**Comment by Delusoire** [comment]
> However, it encounters issues when creating a new playlist with the sorted songs.

I tried sorting a 2k song Playlist and then creating a Sorted Playlist out of that, and it's working fine. I'm sorry but I can't help you if the bug isn't reproducible. Can you try providing more info about this specific issue?
> Additionally, when attempting to reorder the current playlist, especially with large playlists, the app freezes.

This is a limitation of how Spotify does track reordering within a Playlist. I optimized the process as much as possible but the gains are very limited. So unless Spotify improves their implementation, we're stuck with these horrendous reordering times.

**Comment by x-Misery** [comment]
For me nothing happens when creating playlist from queue
![image](https://github.com/Delusoire/spicetify-extensions/assets/156249754/b8badb0f-ad5b-42ab-8e6c-0ae46434f146)
![image](https://github.com/Delusoire/spicetify-extensions/assets/156249754/13c72f43-eb04-439c-b015-9ad53d1e1c81)

**Comment by VPNforWindowsSub** [comment]
I tested sorting a 3k playlist, and it makes the player freeze for about 20 minutes but it works and I can work with it. but, I can't create a new playlist, even with a small sorted playlist. Do I need to edit the folder id in the settings? Here's the error from the console when I try to create a playlist by clicking the + button:

![Error Image](https://github.com/Delusoire/spicetify-extensions/assets/73077542/2809ecd2-a1f3-4d7a-853f-cc6c924d2b39)

**Comment by Delusoire** [comment]
You have to choose a folder where to store the generated playlists before creating the new playlist:
![image](https://github.com/Delusoire/spicetify-extensions/assets/71462480/31906dc9-8f96-4d47-81e2-7ba4260041e6)
But you can also copy paste the folder's URI in this setting:
![image](https://github.com/Delusoire/spicetify-extensions/assets/71462480/650066f5-c669-45e1-ad89-cd9c881c7f91)

**Comment by Delusoire** [comment]
> I tested sorting a 3k playlist, and it makes the player freeze for about 20 minutes but it works and I can work with it.

Is it freezing when sorting the playlist or when reordering it? Because it's not supposed to freeze when sorting.

**Comment by VPNforWindowsSub** [comment]
when reordering

**Comment by Delusoire** [comment]
> > Additionally, when attempting to reorder the current playlist, especially with large playlists, the app freezes.
> 
> This is a limitation of how Spotify does track reordering within a Playlist. I optimized the process as much as possible but the gains are very limited. So unless Spotify improves their implementation, we're stuck with these horrendous reordering times.

Unfortunately, I can't do anything about that 🤷, it's a Spotify issue.
