### ISSUE TITLE
Doesnt sort anything at all

### ISSUE THREAD

**Issue by Molynesio** [Delusoire/spicetify-extensions#23]
Hi, Installed the update from jan 20 a day later, when I try to sort doesnt do anything at all, no messages no queue. Tried doing a complete unninstall from zero, the same things happened except creating a folder withat the yellow flower.
Any help would be apreciated :)
![image](https://github.com/Delusoire/spicetify-extensions/assets/102383268/236a2a6c-ae19-46eb-a2f4-4944ae8c63c0)

**Comment by Delusoire** [comment]
I can't help you without more information about your setup. Because you seem to be the only one having this issue.
Can you send the output of your devtools console, Spotify version & Spicetify version?

**Comment by Molynesio** [comment]
[xpui.app.spotify.com-1705960686797.log](https://github.com/Delusoire/spicetify-extensions/files/14015868/xpui.app.spotify.com-1705960686797.log)

**Comment by Molynesio** [comment]
![image](https://github.com/Delusoire/spicetify-extensions/assets/102383268/daaa926b-979e-43b4-840a-a0fdd66b462d)
When I click on sort by play count that happens
Spotify para Windows (64 bits)
1.2.29.605.g66a43ceb
Spicetify v2.30.0
xpui_2024-01-15_1705312536455_66a43ce
cef_120.2.3+g7d89c0c+chromium-120.0.6099.199
Runtime: Alloy

**Comment by Delusoire** [comment]
Can you type `await Spicetify.GraphQL.Request(Spicetify.GraphQL.Definitions.getAlbum, { uri: "spotify:track:5PyDJG7SQRgWXefgexqIge", locale: Spicetify.Locale.getLocale(), offset: 0, limit: 100 })` in your console?

And just to be sure, does sorting not work on all playlists? Or is it just a special playlist? Because the extension assumes that your playlists don't contain local tracks / episodes ...

**Comment by Molynesio** [comment]
Hell yeah it worked you are amazing!.
But now looks like the playlist doesnt have a personalized picture for each artist any quick fix would be apreciated :).
![image](https://github.com/Delusoire/spicetify-extensions/assets/102383268/75558248-3347-491f-9e83-8a102820dd6e)
(btw thank you so much for the attention, and with updating the best extension from spicetify!. If it wasnt for you I would have already unninstalled spicetify after tetrax left his)

**Comment by birdseed18** [comment]
I believe I have the exact same issue, but when I enter the code provided I receive an error:
![image](https://github.com/Delusoire/spicetify-extensions/assets/157764337/b47ff9ee-2f78-4ffe-9dca-47eded792953)
I have the same exact versions of Spotify and Spicetify, so how to I go about fixing this?

**Comment by Delusoire** [comment]
> I believe I have the exact same issue, but when I enter the code provided I receive an error: ![image](https://private-user-images.githubusercontent.com/157764337/299835846-b47ff9ee-2f78-4ffe-9dca-47eded792953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMjU3NjYsIm5iZiI6MTcwNjIyNTQ2NiwicGF0aCI6Ii8xNTc3NjQzMzcvMjk5ODM1ODQ2LWI0N2ZmOWVlLTJmNzgtNGZmZS05ZGNhLTQ3ZWRlZDc5Mjk1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQyMzMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmNjN2RlMTNiYjg4OTE4ZmE1Y2U3NmNlMzc0OTg3YzY2NGNhZTI4YmRiYWI2YWQ0ZWQ5OTJhN2VlNjJkMWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CguFCbqhd6DMhy57jemMOUjXvnpCJTHq6wuISnKD2V0) I have the same exact versions of Spotify and Spicetify, so how to I go about fixing this?

Can you try this one: `await Spicetify.GraphQL.Request(Spicetify.GraphQL.Definitions.getAlbum, { uri: "spotify:album:0OUOx6rJXtL66AzTnP9KUE", locale: Spicetify.Locale.getLocale(), offset: 0, limit: 100 })`?

**Comment by birdseed18** [comment]
I don't think it fixed anything, unfortunately. :(
![image](https://github.com/Delusoire/spicetify-extensions/assets/157764337/b2cbc6d0-1bd5-4e58-8376-e681ef407692)

**Comment by Delusoire** [comment]
>  I don't think it fixed anything, unfortunately. :(

It's not supposed to fix anything, but this tells me the issue only happens for certain tracks. Can you send me the playlist that you're trying to sort?

**Comment by birdseed18** [comment]
Sure, currently I'm trying to sort this one: https://open.spotify.com/playlist/73YSCqqFrqX7ADOEzu9MBj?si=4bc4341e985d435a
I tried to sort about 15 different playlists, and even some artists, and it never worked, so I'm not sure what specific tracks are causing the issue.

**Comment by Delusoire** [comment]
I fixed it, reload your spotify and it will work. If this problems happens again just send me the playlist and I will be able to fix it. I just had to reduce how many items are requested per batch, because Spotify changed their getAlbum definitions to be more complex requiring more resources per batch.
