### ISSUE TITLE
Bit confused as to what this repo is? 

### ISSUE THREAD

**Issue by CharlieS1103** [Delusoire/spicetify-extensions#6]
As far as I can tell a majority of these extensions have already been made by other people, is there a reason you're reposting them on marketplace?

**Comment by Delusoire** [comment]
This repository is not a repost. All of these extensions have been rewritten to either fix/add features that improve on the older ones. Note that all of these were remade from scratch, with the exception of keyboard-shortcuts.

**Comment by CharlieS1103** [comment]
Ah I see, if that's the case I would at the very least credit the original authors in the marketplace manifest and such
