### ISSUE TITLE
Toggle options

### ISSUE THREAD

**Issue by metya** [Delusoire/spicetify-extensions#9]
Hi! Nine that you've recreated those nice things that could improve our use of Spotify.
And I want to ask, some toggles don't toggle in the settings. 
Here none of the toggles are togglable. Is it the right behavior? 

<img width="1550" alt="image" src="https://github.com/Delusoire/spicetify-extensions/assets/968934/dfc9d9c0-e756-4011-a0ae-f3e83c2ced9c">

**Comment by zesky18** [comment]
In my case, all the toggles don't work at all. The Last.fm Username and API key can't be changed either.

**Comment by Delusoire** [comment]
Thanks for reporting this issue. It is now fixed thanks to 7f61759
